import { z } from 'zod';
import { normalizeTag } from './tags';
import { CATEGORIES } from './categories';

/**
 * CatalogEntrySchema is the shared validation contract for the AI Bazaar catalog.
 *
 * ALL data entering the catalog — whether from scrapers, submission forms, or
 * MCP tool calls — MUST be parsed through this schema before being persisted
 * or returned to callers.
 *
 * Transforms applied at parse time:
 * - tags: normalized to canonical forms and deduplicated (see normalizeTag in tags.ts)
 * - sourceUrl: trailing slash stripped, query params and hash stripped to prevent
 *   dedup failures caused by URL variants pointing to the same resource
 *
 * This enforces catalog invariants (CAT-01 through CAT-04) at the boundary
 * rather than spreading normalization logic across service code.
 */
export const CatalogEntrySchema = z.object({
  /** UUID generated by the database if not provided */
  id: z.string().uuid().optional(),

  /** URL-safe slug for the listing page, e.g. "anthropic-claude-mcp" */
  slug: z
    .string()
    .min(1)
    .max(100)
    .regex(/^[a-z0-9-]+$/, 'Slug must be lowercase alphanumeric with hyphens only'),

  /** Display name of the tool or product */
  name: z.string().min(1).max(100),

  /** Short description for cards and search results (max 160 chars like meta description) */
  tagline: z.string().min(1).max(160),

  /** Full description supporting markdown (max 2000 chars) */
  description: z.string().min(1).max(2000),

  /** Canonical category — must be one of the 6 defined in categories.ts */
  category: z.enum(CATEGORIES),

  /**
   * Tags are normalized to canonical forms and deduplicated at parse time.
   * Input: ['MCP', 'mcp', 'mcpserver'] → Output: ['mcp-server']
   * See TAG_ALIASES in tags.ts for the full alias map.
   */
  tags: z
    .array(z.string())
    .transform((tags) => Array.from(new Set(tags.map(normalizeTag)))),

  /**
   * Canonical source URL — normalized at parse time to prevent dedup failures.
   * Strips trailing slash, query params, and fragment.
   * e.g. "https://github.com/org/repo/" → "https://github.com/org/repo"
   * e.g. "https://example.com/?ref=product-hunt" → "https://example.com"
   */
  sourceUrl: z.string().url().transform((url) => {
    const parsed = new URL(url);
    // Build normalized URL: protocol + hostname + pathname (no query/hash)
    const normalized = `${parsed.protocol}//${parsed.hostname}${parsed.pathname}`;
    // Remove trailing slash from path (but not from root paths like "https://example.com/")
    return normalized.replace(/\/$/, '') || normalized;
  }),

  /** Optional link to documentation */
  docsUrl: z.string().url().optional(),

  /** SPDX license identifier or descriptive string, e.g. "MIT", "Apache-2.0", "Proprietary" */
  licenseType: z.string().optional(),

  /** Primary runtime environment for execution */
  runtime: z.enum(['node', 'python', 'rust', 'go', 'other']).optional(),

  /** Blockchain networks supported, e.g. ["ethereum", "solana", "polygon"] */
  chainSupport: z.array(z.string()).optional(),

  /** Whether this tool implements the Model Context Protocol (MCP) */
  mcpCompatible: z.boolean().default(false),

  /** Whether this tool implements the Agent Communication Protocol (ACP) */
  acpCompatible: z.boolean().default(false),

  /** GitHub stars or equivalent social proof metric */
  stars: z.number().int().min(0).default(0),

  /** npm/PyPI/package registry download count */
  downloads: z.number().int().min(0).default(0),

  /** Timestamp of last automated health/availability check */
  lastVerifiedAt: z.date().optional(),

  /** True if the sourceUrl returns 4xx/5xx — used to flag stale listings */
  deadLink: z.boolean().default(false),

  /** Identifier for who submitted the listing (wallet address, handle, or email) */
  submittedBy: z.string().optional(),

  /** True if a human editor has reviewed and approved this listing */
  verified: z.boolean().default(false),
});

/** Output type — the shape of a CatalogEntry after all transforms have been applied */
export type CatalogEntry = z.infer<typeof CatalogEntrySchema>;

/** Input type — the shape of data before transforms (e.g. tags may have duplicates) */
export type CatalogEntryInput = z.input<typeof CatalogEntrySchema>;

/**
 * Generates a URL-safe slug from a tool name.
 *
 * Used by scrapers and submission handlers to derive slugs automatically.
 * Kept in this file as it is part of the catalog entry contract.
 *
 * @example
 * createSlug('Anthropic Claude MCP') // → 'anthropic-claude-mcp'
 * createSlug('Some Tool v2.0!') // → 'some-tool-v2-0'
 */
export function createSlug(name: string): string {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '')
    .slice(0, 100);
}
